#https://www.skyminds.net/serveur-dedie-backup-manager-sauvegarde-ovh/

export BM_REPOSITORY_ROOT="/save"
export BM_ARCHIVE_TTL="100"
export BM_ARCHIVE_METHOD="tarball-incremental"
export BM_TARBALL_FILETYPE="tar.gz"

export BM_TARBALL_DIRECTORIES="/etc /home /var/lib/mysql"

export BM_MYSQL_ADMINLOGIN="backupuser"
export BM_MYSQL_ADMINPASS="ksGD56gz*-('4ez65g"
export BM_MYSQL_DATABASES="__ALL__"

export BM_UPLOAD_FTP_TIMEOUT="3600"
export BM_UPLOAD_FTP_USER="ksXXXXXXX.kimsufi.com"
export BM_UPLOAD_FTP_PASSWORD="FTP-PASSWORD"
export BM_UPLOAD_FTP_HOSTS="ftpback-XXXX-XXXX.ovh.net"
export BM_UPLOAD_FTP_PURGE="true"
export BM_UPLOAD_FTP_TTL="5"
export BM_UPLOAD_FTP_DESTINATION="/"

export BM_POST_BACKUP_COMMAND="/etc/backup-manager-email"
