[supervisord]
#user = nicolas
nodaemon=true
logfile = /var/log/supervisord.log
logfile_maxbytes = 50MB
logfile_backups=10
startretries=30

[program:cron]
command=/usr/sbin/crond -f
autorestart=false
startretries=30

[program:messenger-consume]
#command=php /srv/api/bin/console messenger:consume async --time-limit=3600
command=php /srv/api/bin/console messenger:consume async --client=xxxxxx --time-limit=3600
#user=nicolas
numprocs=2
startsecs=0
autostart=false
autorestart=true
startretries=30
process_name=%(program_name)s_%(process_num)02d

[program:rsyslog]
command=/sbin/rsyslogd -n -a /var/run/systemd/journal/syslog
numprocs=1
autostart=false
autorestart=true
startretries=30
